"""empty message

Revision ID: 097b0621de65
Revises: 2f1ffe737550
Create Date: 2022-07-27 14:41:43.860993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b0621de65'
down_revision = '2f1ffe737550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todo', 'list', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'list_id')
    # ### end Alembic commands ###
