"""empty message

Revision ID: 1c7bc06b69f9
Revises: 22a99c85e399
Create Date: 2022-07-03 20:51:16.440428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c7bc06b69f9'
down_revision = '22a99c85e399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todo', 'complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
