"""empty message

Revision ID: 22a99c85e399
Revises: 06478bd7f421
Create Date: 2022-07-03 12:52:34.535842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a99c85e399'
down_revision = '06478bd7f421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('complete', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'complete')
    # ### end Alembic commands ###
